### PR TITLE
Fix for #134 Multiple --watchDirectory options throws error

### LINKED ISSUE #134: Multiple --watchDirectory options throws error
This comes from the forever cli project but issue is in the monitor watcher plugin:

**Scenario**: include multiple --watchDirectory='somepaths' in a forever start command.

**Expected**: watch multiple directories
**Actual**: throws exception:
TypeError: Path must be a string. Received [ '/var/www/myproject/services/engine',
  '/var/www/myproject/lib/nodejs' ]
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at exports.attach (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/plugins/watch.js:54:20)
    at Object.bootstrap (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:36:28)
    at exports.App (/usr/local/lib/node_modules/forever/node_modules/broadway/lib/broadway/app.js:47:21)
    at new exports.Monitor (/usr/local/lib/node_modules/forever/node_modules/forever-monitor/lib/forever-monitor/monitor.js:139:16)
    at start (/usr/local/lib/node_modules/forever/bin/monitor:23:17)
    at process.<anonymous> (/usr/local/lib/node_modules/forever/bin/monitor:85:5)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7

It's constructed as a string array as chokidar requests but the watcher plugin throws an exception on line 54 when this.watchDirectory is a string array. It expects a string.

Didn't have time to see if multiple .foreverignore would work, but IMO, the watcher plugin should either iterate through items and use multiple .foreverignore files or use a '.foreverignore' in a single location of the command context instead of the watchDirectory.

LE: watchFilter uses this.watchDirectory too, so that needs fixing as well, so it works with array.

### PR DESCRIPTION
**Pull request by alex7071**
Fixes #134

### CODE REVIEW

**Comment by dasilva333** [comment]
This is a good fix, should be merged

**Comment by xpol** [comment]
I need this too. Please consider merge.

**Comment by alex7071** [comment]
I don't think anyone with write access is maintaining this project anymore. 19 answered pull requests. Consider applying the change locally or checking out the pull branch.

**Comment by kibertoad** [comment]
@alex7071 Thank you for your contribution, looks great!
In order for this to be merged:
1) Documentation needs to be updated - https://github.com/foreverjs/forever-monitor/blob/master/README.md
2) Tests need to be updated. Either add case with multiple watch directories to https://github.com/foreverjs/forever-monitor/blob/master/test/plugins/watch-test.js or create a new Mocha-based one (I intend to phase out vows usage eventually due to absence of IDE support, but it's not there yet).

**Comment by alex7071** [comment]
@kibertoad will do

**Comment by alex7071** [comment]
@kibertoad Sorry for the delay, took a while to remember what all this was about and how tests worked :) Thank you.

**Comment by kibertoad** [comment]
Looks great, thank you!

**Pull request merged**
